"""empty message

Revision ID: ecd48f536574
Revises: 31bb9274ea33
Create Date: 2021-09-08 16:49:46.717352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd48f536574'
down_revision = '31bb9274ea33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'file_id')
    op.drop_table('files')
    # ### end Alembic commands ###
